"""initial postgresql schema

Revision ID: 563c5de3b860
Revises: 
Create Date: 2026-06-20 06:43:12.052329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '563c5de3b860'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('package_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firmware_releases'))
    )
    op.create_index(op.f('ix_firmware_releases_device_model'), 'firmware_releases', ['device_model'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('labels_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('available', 'invalid', 'archived')", name=op.f('ck_models_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('file_path', name=op.f('uq_models_file_path'))
    )
    op.create_index(op.f('ix_models_model_id'), 'models', ['model_id'], unique=True)
    op.create_index('uq_models_one_active', 'models', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('practice_signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sign_id', sa.String(length=100), nullable=False),
    sa.Column('expected_text', sa.String(length=200), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_signs'))
    )
    op.create_index(op.f('ix_practice_signs_sign_id'), 'practice_signs', ['sign_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_role')),
    sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f('ck_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('admin_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('singleton_key', sa.String(length=20), nullable=False),
    sa.Column('system_status', sa.String(length=10), nullable=False),
    sa.Column('active_model_id', sa.UUID(), nullable=True),
    sa.Column('service_toggles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("system_status IN ('on', 'off')", name=op.f('ck_admin_config_system_status')),
    sa.ForeignKeyConstraint(['active_model_id'], ['models.id'], name=op.f('fk_admin_config_active_model_id_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_admin_config_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_config')),
    sa.UniqueConstraint('singleton_key', name=op.f('uq_admin_config_singleton_key'))
    )
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email')),
    sa.UniqueConstraint('firebase_uid', name=op.f('uq_admin_users_firebase_uid'))
    )
    op.create_index(op.f('ix_admin_users_user_id'), 'admin_users', ['user_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('analytics_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_data_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_data')),
    sa.UniqueConstraint('user_id', 'date', 'source', name='analytics_user_date_source')
    )
    op.create_index(op.f('ix_analytics_data_date'), 'analytics_data', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_data_user_id'), 'analytics_data', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('hardware_id', sa.String(length=128), nullable=True),
    sa.Column('connection_status', sa.String(length=30), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('battery_level IS NULL OR (battery_level >= 0 AND battery_level <= 100)', name=op.f('ck_devices_battery')),
    sa.CheckConstraint('signal_strength IS NULL OR (signal_strength >= 0 AND signal_strength <= 5)', name=op.f('ck_devices_signal')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('hardware_id', name=op.f('uq_devices_hardware_id')),
    sa.UniqueConstraint('user_id', 'device_name', name='device_user_name')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('feedback_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'resolved', 'dismissed')", name=op.f('ck_feedback_reports_status')),
    sa.CheckConstraint("type IN ('bug', 'feedback')", name=op.f('ck_feedback_reports_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_reports'))
    )
    op.create_index(op.f('ix_feedback_reports_report_id'), 'feedback_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_feedback_reports_user_id'), 'feedback_reports', ['user_id'], unique=False)
    op.create_table('practice_mode_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sign_id', sa.String(length=100), nullable=False),
    sa.Column('expected_text', sa.String(length=200), nullable=False),
    sa.Column('detected_text', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_practice_mode_data_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_mode_data'))
    )
    op.create_index(op.f('ix_practice_mode_data_sign_id'), 'practice_mode_data', ['sign_id'], unique=False)
    op.create_index(op.f('ix_practice_mode_data_user_id'), 'practice_mode_data', ['user_id'], unique=False)
    op.create_table('smart_house_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=60), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_smart_house_data_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smart_house_data'))
    )
    op.create_index(op.f('ix_smart_house_data_user_id'), 'smart_house_data', ['user_id'], unique=False)
    op.create_table('health_monitor_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_health_monitor_data_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_health_monitor_data_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_monitor_data'))
    )
    op.create_index(op.f('ix_health_monitor_data_timestamp'), 'health_monitor_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_monitor_data_user_id'), 'health_monitor_data', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('translated_letters_count', sa.Integer(), nullable=False),
    sa.Column('total_readings', sa.Integer(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed', 'failed')", name=op.f('ck_sessions_status')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sessions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('uq_sessions_one_active_per_user', 'sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('translation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('gesture_label', sa.String(length=100), nullable=True),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('live', 'mock_seed', 'manual_test')", name=op.f('ck_translation_history_source')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_translation_history_confidence')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_translation_history_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_translation_history_model_id_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_translation_history_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_translation_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_history'))
    )
    op.create_index(op.f('ix_translation_history_entry_id'), 'translation_history', ['entry_id'], unique=True)
    op.create_index(op.f('ix_translation_history_session_id'), 'translation_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_translation_history_timestamp'), 'translation_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_translation_history_user_id'), 'translation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_history_user_id'), table_name='translation_history')
    op.drop_index(op.f('ix_translation_history_timestamp'), table_name='translation_history')
    op.drop_index(op.f('ix_translation_history_session_id'), table_name='translation_history')
    op.drop_index(op.f('ix_translation_history_entry_id'), table_name='translation_history')
    op.drop_table('translation_history')
    op.drop_index('uq_sessions_one_active_per_user', table_name='sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_health_monitor_data_user_id'), table_name='health_monitor_data')
    op.drop_index(op.f('ix_health_monitor_data_timestamp'), table_name='health_monitor_data')
    op.drop_table('health_monitor_data')
    op.drop_index(op.f('ix_smart_house_data_user_id'), table_name='smart_house_data')
    op.drop_table('smart_house_data')
    op.drop_index(op.f('ix_practice_mode_data_user_id'), table_name='practice_mode_data')
    op.drop_index(op.f('ix_practice_mode_data_sign_id'), table_name='practice_mode_data')
    op.drop_table('practice_mode_data')
    op.drop_index(op.f('ix_feedback_reports_user_id'), table_name='feedback_reports')
    op.drop_index(op.f('ix_feedback_reports_report_id'), table_name='feedback_reports')
    op.drop_table('feedback_reports')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_data_user_id'), table_name='analytics_data')
    op.drop_index(op.f('ix_analytics_data_date'), table_name='analytics_data')
    op.drop_table('analytics_data')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_admin_users_user_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('admin_config')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_practice_signs_sign_id'), table_name='practice_signs')
    op.drop_table('practice_signs')
    op.drop_index('uq_models_one_active', table_name='models', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_models_model_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_firmware_releases_device_model'), table_name='firmware_releases')
    op.drop_table('firmware_releases')
    # ### end Alembic commands ###
